# Generated by Django 6.0.1 on 2026-01-13 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classcocurricularconfig',
            options={'ordering': ['created_at']},
        ),
        migrations.AddIndex(
            model_name='schoolconfig',
            index=models.Index(fields=['class_ref', 'session'], name='idx_schoolconfig_class_session'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['class_ref', 'name'], name='idx_section_class_name'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(condition=models.Q(('is_active', True)), fields=['is_active'], name='idx_session_active'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['session', 'class_ref', 'section'], name='idx_stu_sess_cls_sec'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['class_ref', 'section'], name='idx_stu_cls_sec'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['name'], name='idx_stu_name'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['class_ref', 'roll_no'], name='idx_stu_cls_roll'),
        ),
    ]
