# Generated by Django 5.2.10 on 2026-01-17 18:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_services', '0005_student_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(help_text='Short unique identifier for the school', max_length=50, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='school_logos/')),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('alternate_phone', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'School',
                'verbose_name_plural': 'Schools',
                'db_table': 'schools',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveIndex(
            model_name='student',
            name='idx_stu_student_id',
        ),
        migrations.AlterField(
            model_name='cocurricularsubject',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('site_admin', 'Site Admin'), ('admin', 'Admin'), ('teacher', 'Teacher'), ('student', 'Student')], default='teacher', max_length=20),
        ),
        migrations.AlterField(
            model_name='optionalsubject',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(help_text='Permanent unique student identifier per school', max_length=50),
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AddField(
            model_name='admin',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='core_services.school'),
        ),
        migrations.AddField(
            model_name='class',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='core_services.school'),
        ),
        migrations.AddField(
            model_name='cocurricularsubject',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cocurricular_subjects', to='core_services.school'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='school',
            field=models.ForeignKey(blank=True, help_text='School this user belongs to (null for site_admin)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core_services.school'),
        ),
        migrations.AddField(
            model_name='optionalsubject',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='optional_subjects', to='core_services.school'),
        ),
        migrations.AddField(
            model_name='session',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='core_services.school'),
        ),
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='core_services.school'),
        ),
        migrations.AddField(
            model_name='subject',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='core_services.school'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='core_services.school'),
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('school', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='cocurricularsubject',
            unique_together={('school', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='optionalsubject',
            unique_together={('school', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='session',
            unique_together={('school', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('school', 'student_id')},
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('school', 'code')},
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['school', 'is_active'], name='idx_session_school_active'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['school', 'student_id'], name='idx_stu_school_student_id'),
        ),
    ]
