# Generated by Django 5.2.10 on 2026-01-17 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_services', '0006_school_remove_student_idx_stu_student_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='student_id_prefix',
            field=models.CharField(default='STU', help_text='Prefix for auto-generated student IDs', max_length=10),
        ),
    ]
