# Generated by Django 5.2.10 on 2026-01-17 21:05

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_services', '0007_school_student_id_prefix'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="e.g., 'Unit Test 1', 'Mid-Term Exam'", max_length=100)),
                ('code', models.CharField(help_text="e.g., 'UT1', 'MT', 'FINAL'", max_length=50)),
                ('category_type', models.CharField(choices=[('summative', 'Summative'), ('formative', 'Formative'), ('project', 'Project'), ('practical', 'Practical'), ('other', 'Other')], default='summative', max_length=20)),
                ('display_order', models.IntegerField(default=0, help_text='Order in which this appears in UI')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_categories', to='core_services.school')),
            ],
            options={
                'db_table': 'assessment_categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CocurricularMarksDistribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_marks', models.IntegerField(help_text='Full marks for this assessment')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cocurricular_distributions', to='core_services.assessmentcategory')),
                ('class_ref', models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, related_name='cocurricular_marks_distributions', to='core_services.class')),
                ('cocurricular_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks_distributions', to='core_services.cocurricularsubject')),
            ],
            options={
                'db_table': 'cocurricular_marks_distributions',
            },
        ),
        migrations.CreateModel(
            name='CoreSubjectMarksDistribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_marks', models.IntegerField(help_text='Full marks for this assessment')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_distributions', to='core_services.assessmentcategory')),
                ('class_ref', models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, related_name='core_marks_distributions', to='core_services.class')),
            ],
            options={
                'db_table': 'core_subject_marks_distributions',
            },
        ),
        migrations.CreateModel(
            name='OptionalMarksDistribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_marks', models.IntegerField(help_text='Full marks for this assessment')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optional_distributions', to='core_services.assessmentcategory')),
                ('class_ref', models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, related_name='optional_marks_distributions', to='core_services.class')),
                ('optional_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks_distributions', to='core_services.optionalsubject')),
            ],
            options={
                'db_table': 'optional_marks_distributions',
            },
        ),
        migrations.AddIndex(
            model_name='assessmentcategory',
            index=models.Index(fields=['school', 'is_active'], name='idx_ac_school_active'),
        ),
        migrations.AddIndex(
            model_name='assessmentcategory',
            index=models.Index(fields=['display_order'], name='idx_ac_display_order'),
        ),
        migrations.AlterUniqueTogether(
            name='assessmentcategory',
            unique_together={('school', 'code')},
        ),
        migrations.AddIndex(
            model_name='cocurricularmarksdistribution',
            index=models.Index(fields=['class_ref', 'cocurricular_subject'], name='idx_ccmd_class_subject'),
        ),
        migrations.AlterUniqueTogether(
            name='cocurricularmarksdistribution',
            unique_together={('class_ref', 'cocurricular_subject', 'assessment_category')},
        ),
        migrations.AddIndex(
            model_name='coresubjectmarksdistribution',
            index=models.Index(fields=['class_ref'], name='idx_csmd_class'),
        ),
        migrations.AlterUniqueTogether(
            name='coresubjectmarksdistribution',
            unique_together={('class_ref', 'assessment_category')},
        ),
        migrations.AddIndex(
            model_name='optionalmarksdistribution',
            index=models.Index(fields=['class_ref', 'optional_subject'], name='idx_omd_class_subject'),
        ),
        migrations.AlterUniqueTogether(
            name='optionalmarksdistribution',
            unique_together={('class_ref', 'optional_subject', 'assessment_category')},
        ),
    ]
