# Generated by Django 5.2.10 on 2026-01-17 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_services', '0006_school_remove_student_idx_stu_student_id_and_more'),
        ('payments_management', '0002_add_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='feediscount',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_discounts', to='core_services.school'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='core_services.school'),
        ),
        migrations.AddField(
            model_name='payment',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core_services.school'),
        ),
        migrations.AddField(
            model_name='paymentreminder',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_reminders', to='core_services.school'),
        ),
        migrations.AddField(
            model_name='studentfee',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_fees', to='core_services.school'),
        ),
    ]
