# Generated by Django 6.0.1 on 2026-01-14 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_services', '0004_classteacher_cocurricularteacherassignment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='student_photos/'),
        ),
    ]
