# Generated by Django 6.0.1 on 2026-01-13 17:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_services', '0002_add_indexes'),
        ('payments_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='feestructure',
            index=models.Index(fields=['class_ref', 'session'], name='idx_feestructure_class_session'),
        ),
        migrations.AddIndex(
            model_name='feestructure',
            index=models.Index(condition=models.Q(('is_active', True)), fields=['is_active'], name='idx_feestructure_active'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_date'], name='idx_payment_date'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_method', 'payment_date'], name='idx_payment_method_date'),
        ),
        migrations.AddIndex(
            model_name='studentfee',
            index=models.Index(fields=['student', 'session'], name='idx_studentfee_student_session'),
        ),
        migrations.AddIndex(
            model_name='studentfee',
            index=models.Index(condition=models.Q(('status__in', ['pending', 'partial', 'overdue'])), fields=['status'], name='idx_studentfee_pending'),
        ),
        migrations.AddIndex(
            model_name='studentfee',
            index=models.Index(fields=['due_date', 'status'], name='idx_studentfee_duedate_status'),
        ),
    ]
